# https://ftx.com/settings/api
API_KEY = ""
SECRET_KEY = ""

SYMBOL = "ETH/USD"
POSITION_SIZE = 0.001

# BOT SETTINGS
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 3

CHECK_ORDERS_FREQUENCY = 2
CLOSED_ORDER_STATUS = 'closed'

